# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-compulab-rpi5"
BBFILE_PATTERN_meta-compulab-rpi5 = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-compulab-rpi5 = "6"

LAYERDEPENDS_meta-compulab-rpi5 = "core"
LAYERSERIES_COMPAT_meta-compulab-rpi5 = "wrynose"

CORE_IMAGE_EXTRA_INSTALL:append = " usbutils pciutils coreutils nfs-utils i2c-tools "
CORE_IMAGE_EXTRA_INSTALL:append = " kernel-modules "
CORE_IMAGE_EXTRA_INSTALL:append = " libubootenv-bin u-boot-env "
CORE_IMAGE_EXTRA_INSTALL:append = " iperf3 "

# Allows root to login without a password
# Automatically logs in as root on the serial console
IMAGE_FEATURES:append = " empty-root-password "
IMAGE_FEATURES:append = " serial-autologin-root "

INHERIT += "compulab_image-rpi"

SERIAL_CONSOLES = "115200;ttyS0 115200;ttyGS0"
